spring.application.name=McpServerApplication
spring.main.web-application-type = none
spring.ai.mcp.server.version = 0.0.1

spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.stdio=true

spring.main.banner.mode=off
donaciones.base-url=${DONACIONES_BASE_URL:https://donaciones-1-7xzd.onrender.com}
logistical.base-url=${LOGISTICA_BASE_URL:https://logistica-entrega3.onrender.com}