spring.application.name=McpServerApplication
spring.main.web-application-type = none
spring.ai.mcp.server.version = 0.0.1

spring.ai.mcp.server.enabled=true
spring.ai.mcp.server.stdio=true

spring.main.banner.mode=off

DONACIONES_API_URL=https://donaciones-1-7xzd.onrender.com
LOGISTICA_API_URL=https://logistica-entrega3.onrender.com
INCENTIVOS_API_URL=https://entrega-2-lseijasferraudo.onrender.com
DONADORES_ENTIDADES_API_URL=https://donadoresyentidades-hxss.onrender.com

spring.autoconfigure.exclude=org.springframework.cloud.client.discovery.simple.SimpleDiscoveryClientAutoConfiguration
logging.level.org.springframework.ai=INFO
logging.pattern.console=
